/*
 * Project name:
     Pressure4_demo_app.mcpar
 * Generated by:
     Visual TFT
 * Date of creation
     26.6.2018.
 * Test configuration:
     MCU:             STM32F746ZG
     Dev.Board:       Mikromedia_Plus_for_STM32F7_ARM
     Oscillator:      216000000 Hz
     SW:              mikroC PRO for ARM
                      http://www.mikroe.com/mikroc/arm/
 */

#include "Pressure4_demo_app_objects.h"

void main() {

  Start_TP();

  while (1) {
    Check_TP();
  }
}